## Append samples of your project ##
resources:
- infrastructure_v1beta1_ktmachinetemplate.yaml
- infrastructure_v1beta1_ktcluster.yaml
- infrastructure_v1beta1_cluster.yaml
- infrastructure_v1beta1_kubeadmconfigtemplate.yaml
- infrastructure_v1beta1_kubeadmcontrolplane.yaml
- infrastructure_v1beta1_machinedeployment.yaml
- infrastructure_v1beta1_ktsubjecttoken.yaml
- infrastructure_v1beta1_ktmachine.yaml
- infrastructure_v1beta1_ktpublicnetwork.yaml
- infrastructure_v1beta1_ktnetworkfirewall.yaml
- infrastructure_v1beta1_clustercontrolplanedeployment.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
